// <auto-generated />
using System;
using FurnitureShop.Backend.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureShop.Backend.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221023064303_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Buyer", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.HasIndex("NumberPhone")
                        .IsUnique();

                    b.ToTable("Buyer", (string)null);
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Contract", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<int>("BuyerCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Number");

                    b.HasIndex("BuyerCode");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Furniture", b =>
                {
                    b.Property<int>("Model")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Model"), 1L, 1);

                    b.Property<string>("Characteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Model");

                    b.ToTable("Furniture", (string)null);
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Sale", b =>
                {
                    b.Property<int>("ContractNumber")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureModel")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("ContractNumber", "FurnitureModel");

                    b.HasIndex("FurnitureModel");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Contract", b =>
                {
                    b.HasOne("FurnitureShop.Backend.DataAccess.Entities.Buyer", "Buyer")
                        .WithMany("Contracts")
                        .HasForeignKey("BuyerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Sale", b =>
                {
                    b.HasOne("FurnitureShop.Backend.DataAccess.Entities.Contract", "Contract")
                        .WithMany("Sales")
                        .HasForeignKey("ContractNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurnitureShop.Backend.DataAccess.Entities.Furniture", "Furniture")
                        .WithMany("Sales")
                        .HasForeignKey("FurnitureModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Buyer", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Contract", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("FurnitureShop.Backend.DataAccess.Entities.Furniture", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
